package countrymeta

import (
	"regexp"
)

func init() {
	Registry = map[string]Meta{
		"AD": {
			Country: "AD",
			Name: "Andorra",
			Length: 24,
			Regex: regexp.MustCompile("^AD[0-9]{2}[0-9]{4}[0-9]{4}[A-Za-z0-9]{12}$"),
			BankStart: 1,
			BankEnd: 4,
			AccountStart: 5,
			AccountEnd: 8,
		},
		"AE": {
			Country: "AE",
			Name: "United Arab Emirates (The)",
			Length: 23,
			Regex: regexp.MustCompile("^AE[0-9]{2}[0-9]{3}[0-9]{16}$"),
			BankStart: 1,
			BankEnd: 3,
			AccountStart: 4,
			AccountEnd: 19,
		},
		"AL": {
			Country: "AL",
			Name: "Albania",
			Length: 28,
			Regex: regexp.MustCompile("^AL[0-9]{2}[0-9]{8}[A-Za-z0-9]{16}$"),
			BankStart: 1,
			BankEnd: 8,
			AccountStart: 9,
			AccountEnd: 24,
		},
		"AT": {
			Country: "AT",
			Name: "Austria",
			Length: 20,
			Regex: regexp.MustCompile("^AT[0-9]{2}[0-9]{5}[0-9]{11}$"),
			BankStart: 1,
			BankEnd: 5,
			AccountStart: 6,
			AccountEnd: 16,
		},
		"AZ": {
			Country: "AZ",
			Name: "Azerbaijan",
			Length: 28,
			Regex: regexp.MustCompile("^AZ[0-9]{2}[A-Z]{4}[A-Za-z0-9]{20}$"),
			BankStart: 1,
			BankEnd: 4,
			AccountStart: 5,
			AccountEnd: 24,
		},
		"BA": {
			Country: "BA",
			Name: "Bosnia and Herzegovina",
			Length: 20,
			Regex: regexp.MustCompile("^BA[0-9]{2}[0-9]{3}[0-9]{3}[0-9]{8}[0-9]{2}$"),
			BankStart: 1,
			BankEnd: 3,
			AccountStart: 4,
			AccountEnd: 6,
		},
		"BE": {
			Country: "BE",
			Name: "Belgium",
			Length: 16,
			Regex: regexp.MustCompile("^BE[0-9]{2}[0-9]{3}[0-9]{7}[0-9]{2}$"),
			BankStart: 1,
			BankEnd: 3,
			AccountStart: 4,
			AccountEnd: 10,
		},
		"BG": {
			Country: "BG",
			Name: "Bulgaria",
			Length: 22,
			Regex: regexp.MustCompile("^BG[0-9]{2}[A-Z]{4}[0-9]{4}[0-9]{2}[A-Za-z0-9]{8}$"),
			BankStart: 1,
			BankEnd: 4,
			AccountStart: 5,
			AccountEnd: 8,
		},
		"BH": {
			Country: "BH",
			Name: "Bahrain",
			Length: 22,
			Regex: regexp.MustCompile("^BH[0-9]{2}[A-Z]{4}[A-Za-z0-9]{14}$"),
			BankStart: 1,
			BankEnd: 4,
			AccountStart: 5,
			AccountEnd: 18,
		},
		"BI": {
			Country: "BI",
			Name: "Burundi",
			Length: 27,
			Regex: regexp.MustCompile("^BI[0-9]{2}[0-9]{5}[0-9]{5}[0-9]{11}[0-9]{2}$"),
			BankStart: 1,
			BankEnd: 5,
			AccountStart: 6,
			AccountEnd: 10,
		},
		"BR": {
			Country: "BR",
			Name: "Brazil",
			Length: 29,
			Regex: regexp.MustCompile("^BR[0-9]{2}[0-9]{8}[0-9]{5}[0-9]{10}[A-Z]{1}[A-Za-z0-9]{1}$"),
			BankStart: 1,
			BankEnd: 8,
			AccountStart: 9,
			AccountEnd: 13,
		},
		"BY": {
			Country: "BY",
			Name: "Republic of Belarus",
			Length: 28,
			Regex: regexp.MustCompile("^BY[0-9]{2}[A-Za-z0-9]{4}[0-9]{4}[A-Za-z0-9]{16}$"),
			BankStart: 1,
			BankEnd: 4,
			AccountStart: 5,
			AccountEnd: 8,
		},
		"CH": {
			Country: "CH",
			Name: "Switzerland",
			Length: 21,
			Regex: regexp.MustCompile("^CH[0-9]{2}[0-9]{5}[A-Za-z0-9]{12}$"),
			BankStart: 1,
			BankEnd: 5,
			AccountStart: 6,
			AccountEnd: 17,
		},
		"CR": {
			Country: "CR",
			Name: "Costa Rica",
			Length: 22,
			Regex: regexp.MustCompile("^CR[0-9]{2}[0-9]{4}[0-9]{14}$"),
			BankStart: 1,
			BankEnd: 4,
			AccountStart: 5,
			AccountEnd: 18,
		},
		"CY": {
			Country: "CY",
			Name: "Cyprus",
			Length: 28,
			Regex: regexp.MustCompile("^CY[0-9]{2}[0-9]{3}[0-9]{5}[A-Za-z0-9]{16}$"),
			BankStart: 1,
			BankEnd: 3,
			AccountStart: 4,
			AccountEnd: 8,
		},
		"CZ": {
			Country: "CZ",
			Name: "Czechia",
			Length: 24,
			Regex: regexp.MustCompile("^CZ[0-9]{2}[0-9]{4}[0-9]{6}[0-9]{10}$"),
			BankStart: 1,
			BankEnd: 4,
			AccountStart: 5,
			AccountEnd: 10,
		},
		"DE": {
			Country: "DE",
			Name: "Germany",
			Length: 22,
			Regex: regexp.MustCompile("^DE[0-9]{2}[0-9]{8}[0-9]{10}$"),
			BankStart: 1,
			BankEnd: 8,
			AccountStart: 9,
			AccountEnd: 18,
		},
		"DJ": {
			Country: "DJ",
			Name: "Djibouti",
			Length: 27,
			Regex: regexp.MustCompile("^DJ[0-9]{2}[0-9]{5}[0-9]{5}[0-9]{11}[0-9]{2}$"),
			BankStart: 1,
			BankEnd: 5,
			AccountStart: 6,
			AccountEnd: 10,
		},
		"DK": {
			Country: "DK",
			Name: "Denmark",
			Length: 18,
			Regex: regexp.MustCompile("^DK[0-9]{2}[0-9]{4}[0-9]{9}[0-9]{1}$"),
			BankStart: 1,
			BankEnd: 4,
			AccountStart: 5,
			AccountEnd: 13,
		},
		"DO": {
			Country: "DO",
			Name: "Dominican Republic",
			Length: 28,
			Regex: regexp.MustCompile("^DO[0-9]{2}[A-Za-z0-9]{4}[0-9]{20}$"),
			BankStart: 1,
			BankEnd: 4,
			AccountStart: 5,
			AccountEnd: 24,
		},
		"EE": {
			Country: "EE",
			Name: "Estonia",
			Length: 20,
			Regex: regexp.MustCompile("^EE[0-9]{2}[0-9]{2}[0-9]{14}$"),
			BankStart: 1,
			BankEnd: 2,
			AccountStart: 3,
			AccountEnd: 16,
		},
		"EG": {
			Country: "EG",
			Name: "Egypt",
			Length: 29,
			Regex: regexp.MustCompile("^EG[0-9]{2}[0-9]{4}[0-9]{4}[0-9]{17}$"),
			BankStart: 1,
			BankEnd: 4,
			AccountStart: 5,
			AccountEnd: 8,
		},
		"ES": {
			Country: "ES",
			Name: "Spain",
			Length: 24,
			Regex: regexp.MustCompile("^ES[0-9]{2}[0-9]{4}[0-9]{4}[0-9]{1}[0-9]{1}[0-9]{10}$"),
			BankStart: 1,
			BankEnd: 4,
			AccountStart: 5,
			AccountEnd: 8,
		},
		"FI": {
			Country: "FI",
			Name: "Finland",
			Length: 18,
			Regex: regexp.MustCompile("^FI[0-9]{2}[0-9]{3}[0-9]{11}$"),
			BankStart: 1,
			BankEnd: 3,
			AccountStart: 4,
			AccountEnd: 14,
		},
		"FK": {
			Country: "FK",
			Name: "Falkland Islands",
			Length: 18,
			Regex: regexp.MustCompile("^FK[0-9]{2}[A-Z]{2}[0-9]{12}$"),
			BankStart: 1,
			BankEnd: 2,
			AccountStart: 3,
			AccountEnd: 14,
		},
		"FO": {
			Country: "FO",
			Name: "Faroe Islands",
			Length: 18,
			Regex: regexp.MustCompile("^FO[0-9]{2}[0-9]{4}[0-9]{9}[0-9]{1}$"),
			BankStart: 1,
			BankEnd: 4,
			AccountStart: 5,
			AccountEnd: 13,
		},
		"FR": {
			Country: "FR",
			Name: "France",
			Length: 27,
			Regex: regexp.MustCompile("^FR[0-9]{2}[0-9]{5}[0-9]{5}[A-Za-z0-9]{11}[0-9]{2}$"),
			BankStart: 1,
			BankEnd: 5,
			AccountStart: 6,
			AccountEnd: 10,
		},
		"GB": {
			Country: "GB",
			Name: "United Kingdom",
			Length: 22,
			Regex: regexp.MustCompile("^GB[0-9]{2}[A-Z]{4}[0-9]{6}[0-9]{8}$"),
			BankStart: 1,
			BankEnd: 4,
			AccountStart: 5,
			AccountEnd: 10,
		},
		"GE": {
			Country: "GE",
			Name: "Georgia",
			Length: 22,
			Regex: regexp.MustCompile("^GE[0-9]{2}[A-Z]{2}[0-9]{16}$"),
			BankStart: 1,
			BankEnd: 2,
			AccountStart: 3,
			AccountEnd: 18,
		},
		"GI": {
			Country: "GI",
			Name: "Gibraltar",
			Length: 23,
			Regex: regexp.MustCompile("^GI[0-9]{2}[A-Z]{4}[A-Za-z0-9]{15}$"),
			BankStart: 1,
			BankEnd: 4,
			AccountStart: 5,
			AccountEnd: 19,
		},
		"GL": {
			Country: "GL",
			Name: "Greenland",
			Length: 18,
			Regex: regexp.MustCompile("^GL[0-9]{2}[0-9]{4}[0-9]{9}[0-9]{1}$"),
			BankStart: 1,
			BankEnd: 4,
			AccountStart: 5,
			AccountEnd: 13,
		},
		"GR": {
			Country: "GR",
			Name: "Greece",
			Length: 27,
			Regex: regexp.MustCompile("^GR[0-9]{2}[0-9]{3}[0-9]{4}[A-Za-z0-9]{16}$"),
			BankStart: 1,
			BankEnd: 3,
			AccountStart: 4,
			AccountEnd: 7,
		},
		"GT": {
			Country: "GT",
			Name: "Guatemala",
			Length: 28,
			Regex: regexp.MustCompile("^GT[0-9]{2}[A-Za-z0-9]{4}[A-Za-z0-9]{20}$"),
			BankStart: 1,
			BankEnd: 4,
			AccountStart: 5,
			AccountEnd: 24,
		},
		"HN": {
			Country: "HN",
			Name: "Honduras",
			Length: 28,
			Regex: regexp.MustCompile("^HN[0-9]{2}[A-Z]{4}[0-9]{20}$"),
			BankStart: 1,
			BankEnd: 4,
			AccountStart: 5,
			AccountEnd: 24,
		},
		"HR": {
			Country: "HR",
			Name: "Croatia",
			Length: 21,
			Regex: regexp.MustCompile("^HR[0-9]{2}[0-9]{7}[0-9]{10}$"),
			BankStart: 1,
			BankEnd: 7,
			AccountStart: 8,
			AccountEnd: 17,
		},
		"HU": {
			Country: "HU",
			Name: "Hungary",
			Length: 28,
			Regex: regexp.MustCompile("^HU[0-9]{2}[0-9]{3}[0-9]{4}[0-9]{1}[0-9]{15}[0-9]{1}$"),
			BankStart: 1,
			BankEnd: 3,
			AccountStart: 4,
			AccountEnd: 7,
		},
		"IE": {
			Country: "IE",
			Name: "Ireland",
			Length: 22,
			Regex: regexp.MustCompile("^IE[0-9]{2}[A-Z]{4}[0-9]{6}[0-9]{8}$"),
			BankStart: 1,
			BankEnd: 4,
			AccountStart: 5,
			AccountEnd: 10,
		},
		"IL": {
			Country: "IL",
			Name: "Israel",
			Length: 23,
			Regex: regexp.MustCompile("^IL[0-9]{2}[0-9]{3}[0-9]{3}[0-9]{13}$"),
			BankStart: 1,
			BankEnd: 3,
			AccountStart: 4,
			AccountEnd: 6,
		},
		"IQ": {
			Country: "IQ",
			Name: "Iraq",
			Length: 23,
			Regex: regexp.MustCompile("^IQ[0-9]{2}[A-Z]{4}[0-9]{3}[0-9]{12}$"),
			BankStart: 1,
			BankEnd: 4,
			AccountStart: 5,
			AccountEnd: 7,
		},
		"IS": {
			Country: "IS",
			Name: "Iceland",
			Length: 26,
			Regex: regexp.MustCompile("^IS[0-9]{2}[0-9]{4}[0-9]{2}[0-9]{6}[0-9]{10}$"),
			BankStart: 1,
			BankEnd: 4,
			AccountStart: 5,
			AccountEnd: 6,
		},
		"IT": {
			Country: "IT",
			Name: "Italy",
			Length: 27,
			Regex: regexp.MustCompile("^IT[0-9]{2}[A-Z]{1}[0-9]{5}[0-9]{5}[A-Za-z0-9]{12}$"),
			BankStart: 1,
			BankEnd: 1,
			AccountStart: 2,
			AccountEnd: 6,
		},
		"JO": {
			Country: "JO",
			Name: "Jordan",
			Length: 30,
			Regex: regexp.MustCompile("^JO[0-9]{2}[A-Z]{4}[0-9]{4}[A-Za-z0-9]{18}$"),
			BankStart: 1,
			BankEnd: 4,
			AccountStart: 5,
			AccountEnd: 8,
		},
		"KW": {
			Country: "KW",
			Name: "Kuwait",
			Length: 30,
			Regex: regexp.MustCompile("^KW[0-9]{2}[A-Z]{4}[A-Za-z0-9]{22}$"),
			BankStart: 1,
			BankEnd: 4,
			AccountStart: 5,
			AccountEnd: 26,
		},
		"KZ": {
			Country: "KZ",
			Name: "Kazakhstan",
			Length: 20,
			Regex: regexp.MustCompile("^KZ[0-9]{2}[0-9]{3}[A-Za-z0-9]{13}$"),
			BankStart: 1,
			BankEnd: 3,
			AccountStart: 4,
			AccountEnd: 16,
		},
		"LB": {
			Country: "LB",
			Name: "Lebanon",
			Length: 28,
			Regex: regexp.MustCompile("^LB[0-9]{2}[0-9]{4}[A-Za-z0-9]{20}$"),
			BankStart: 1,
			BankEnd: 4,
			AccountStart: 5,
			AccountEnd: 24,
		},
		"LC": {
			Country: "LC",
			Name: "Saint Lucia",
			Length: 32,
			Regex: regexp.MustCompile("^LC[0-9]{2}[A-Z]{4}[A-Za-z0-9]{24}$"),
			BankStart: 1,
			BankEnd: 4,
			AccountStart: 5,
			AccountEnd: 28,
		},
		"LI": {
			Country: "LI",
			Name: "Liechtenstein",
			Length: 21,
			Regex: regexp.MustCompile("^LI[0-9]{2}[0-9]{5}[A-Za-z0-9]{12}$"),
			BankStart: 1,
			BankEnd: 5,
			AccountStart: 6,
			AccountEnd: 17,
		},
		"LT": {
			Country: "LT",
			Name: "Lithuania",
			Length: 20,
			Regex: regexp.MustCompile("^LT[0-9]{2}[0-9]{5}[0-9]{11}$"),
			BankStart: 1,
			BankEnd: 5,
			AccountStart: 6,
			AccountEnd: 16,
		},
		"LU": {
			Country: "LU",
			Name: "Luxembourg",
			Length: 20,
			Regex: regexp.MustCompile("^LU[0-9]{2}[0-9]{3}[A-Za-z0-9]{13}$"),
			BankStart: 1,
			BankEnd: 3,
			AccountStart: 4,
			AccountEnd: 16,
		},
		"LV": {
			Country: "LV",
			Name: "Latvia",
			Length: 21,
			Regex: regexp.MustCompile("^LV[0-9]{2}[A-Z]{4}[A-Za-z0-9]{13}$"),
			BankStart: 1,
			BankEnd: 4,
			AccountStart: 5,
			AccountEnd: 17,
		},
		"LY": {
			Country: "LY",
			Name: "Libya",
			Length: 25,
			Regex: regexp.MustCompile("^LY[0-9]{2}[0-9]{3}[0-9]{3}[0-9]{15}$"),
			BankStart: 1,
			BankEnd: 3,
			AccountStart: 4,
			AccountEnd: 6,
		},
		"MC": {
			Country: "MC",
			Name: "Monaco",
			Length: 27,
			Regex: regexp.MustCompile("^MC[0-9]{2}[0-9]{5}[0-9]{5}[A-Za-z0-9]{11}[0-9]{2}$"),
			BankStart: 1,
			BankEnd: 5,
			AccountStart: 6,
			AccountEnd: 10,
		},
		"MD": {
			Country: "MD",
			Name: "Moldova",
			Length: 24,
			Regex: regexp.MustCompile("^MD[0-9]{2}[A-Za-z0-9]{2}[A-Za-z0-9]{18}$"),
			BankStart: 1,
			BankEnd: 2,
			AccountStart: 3,
			AccountEnd: 20,
		},
		"ME": {
			Country: "ME",
			Name: "Montenegro",
			Length: 22,
			Regex: regexp.MustCompile("^ME[0-9]{2}[0-9]{3}[0-9]{13}[0-9]{2}$"),
			BankStart: 1,
			BankEnd: 3,
			AccountStart: 4,
			AccountEnd: 16,
		},
		"MK": {
			Country: "MK",
			Name: "Macedonia",
			Length: 19,
			Regex: regexp.MustCompile("^MK[0-9]{2}[0-9]{3}[A-Za-z0-9]{10}[0-9]{2}$"),
			BankStart: 1,
			BankEnd: 3,
			AccountStart: 4,
			AccountEnd: 13,
		},
		"MN": {
			Country: "MN",
			Name: "Mongolia",
			Length: 20,
			Regex: regexp.MustCompile("^MN[0-9]{2}[0-9]{4}[0-9]{12}$"),
			BankStart: 1,
			BankEnd: 4,
			AccountStart: 5,
			AccountEnd: 16,
		},
		"MR": {
			Country: "MR",
			Name: "Mauritania",
			Length: 27,
			Regex: regexp.MustCompile("^MR[0-9]{2}[0-9]{5}[0-9]{5}[0-9]{11}[0-9]{2}$"),
			BankStart: 1,
			BankEnd: 5,
			AccountStart: 6,
			AccountEnd: 10,
		},
		"MT": {
			Country: "MT",
			Name: "Malta",
			Length: 31,
			Regex: regexp.MustCompile("^MT[0-9]{2}[A-Z]{4}[0-9]{5}[A-Za-z0-9]{18}$"),
			BankStart: 1,
			BankEnd: 4,
			AccountStart: 5,
			AccountEnd: 9,
		},
		"MU": {
			Country: "MU",
			Name: "Mauritius",
			Length: 30,
			Regex: regexp.MustCompile("^MU[0-9]{2}[A-Z]{4}[0-9]{2}[0-9]{2}[0-9]{12}[0-9]{3}[A-Z]{3}$"),
			BankStart: 1,
			BankEnd: 4,
			AccountStart: 5,
			AccountEnd: 6,
		},
		"NI": {
			Country: "NI",
			Name: "Nicaragua",
			Length: 28,
			Regex: regexp.MustCompile("^NI[0-9]{2}[A-Z]{4}[0-9]{20}$"),
			BankStart: 1,
			BankEnd: 4,
			AccountStart: 5,
			AccountEnd: 24,
		},
		"NL": {
			Country: "NL",
			Name: "Netherlands (The)",
			Length: 18,
			Regex: regexp.MustCompile("^NL[0-9]{2}[A-Z]{4}[0-9]{10}$"),
			BankStart: 1,
			BankEnd: 4,
			AccountStart: 5,
			AccountEnd: 14,
		},
		"NO": {
			Country: "NO",
			Name: "Norway",
			Length: 15,
			Regex: regexp.MustCompile("^NO[0-9]{2}[0-9]{4}[0-9]{6}[0-9]{1}$"),
			BankStart: 1,
			BankEnd: 4,
			AccountStart: 5,
			AccountEnd: 10,
		},
		"OM": {
			Country: "OM",
			Name: "Oman",
			Length: 23,
			Regex: regexp.MustCompile("^OM[0-9]{2}[0-9]{3}[A-Za-z0-9]{16}$"),
			BankStart: 1,
			BankEnd: 3,
			AccountStart: 4,
			AccountEnd: 19,
		},
		"PK": {
			Country: "PK",
			Name: "Pakistan",
			Length: 24,
			Regex: regexp.MustCompile("^PK[0-9]{2}[A-Z]{4}[A-Za-z0-9]{16}$"),
			BankStart: 1,
			BankEnd: 4,
			AccountStart: 5,
			AccountEnd: 20,
		},
		"PL": {
			Country: "PL",
			Name: "Poland",
			Length: 28,
			Regex: regexp.MustCompile("^PL[0-9]{2}[0-9]{8}[0-9]{16}$"),
			BankStart: 1,
			BankEnd: 8,
			AccountStart: 9,
			AccountEnd: 24,
		},
		"PS": {
			Country: "PS",
			Name: "\"Palestine, State of\"",
			Length: 29,
			Regex: regexp.MustCompile("^PS[0-9]{2}[A-Z]{4}[A-Za-z0-9]{21}$"),
			BankStart: 1,
			BankEnd: 4,
			AccountStart: 5,
			AccountEnd: 25,
		},
		"PT": {
			Country: "PT",
			Name: "Portugal",
			Length: 25,
			Regex: regexp.MustCompile("^PT[0-9]{2}[0-9]{4}[0-9]{4}[0-9]{11}[0-9]{2}$"),
			BankStart: 1,
			BankEnd: 4,
			AccountStart: 5,
			AccountEnd: 8,
		},
		"QA": {
			Country: "QA",
			Name: "Qatar",
			Length: 29,
			Regex: regexp.MustCompile("^QA[0-9]{2}[A-Z]{4}[A-Za-z0-9]{21}$"),
			BankStart: 1,
			BankEnd: 4,
			AccountStart: 5,
			AccountEnd: 25,
		},
		"RO": {
			Country: "RO",
			Name: "Romania",
			Length: 24,
			Regex: regexp.MustCompile("^RO[0-9]{2}[A-Z]{4}[A-Za-z0-9]{16}$"),
			BankStart: 1,
			BankEnd: 4,
			AccountStart: 5,
			AccountEnd: 20,
		},
		"RS": {
			Country: "RS",
			Name: "Serbia",
			Length: 22,
			Regex: regexp.MustCompile("^RS[0-9]{2}[0-9]{3}[0-9]{13}[0-9]{2}$"),
			BankStart: 1,
			BankEnd: 3,
			AccountStart: 4,
			AccountEnd: 16,
		},
		"RU": {
			Country: "RU",
			Name: "Russia",
			Length: 33,
			Regex: regexp.MustCompile("^RU[0-9]{2}[0-9]{9}[0-9]{5}[A-Za-z0-9]{15}$"),
			BankStart: 1,
			BankEnd: 9,
			AccountStart: 10,
			AccountEnd: 14,
		},
		"SA": {
			Country: "SA",
			Name: "Saudi Arabia",
			Length: 24,
			Regex: regexp.MustCompile("^SA[0-9]{2}[0-9]{2}[A-Za-z0-9]{18}$"),
			BankStart: 1,
			BankEnd: 2,
			AccountStart: 3,
			AccountEnd: 20,
		},
		"SC": {
			Country: "SC",
			Name: "Seychelles",
			Length: 31,
			Regex: regexp.MustCompile("^SC[0-9]{2}[A-Z]{4}[0-9]{2}[0-9]{2}[0-9]{16}[A-Z]{3}$"),
			BankStart: 1,
			BankEnd: 4,
			AccountStart: 5,
			AccountEnd: 6,
		},
		"SD": {
			Country: "SD",
			Name: "Sudan",
			Length: 18,
			Regex: regexp.MustCompile("^SD[0-9]{2}[0-9]{2}[0-9]{12}$"),
			BankStart: 1,
			BankEnd: 2,
			AccountStart: 3,
			AccountEnd: 14,
		},
		"SE": {
			Country: "SE",
			Name: "Sweden",
			Length: 24,
			Regex: regexp.MustCompile("^SE[0-9]{2}[0-9]{3}[0-9]{16}[0-9]{1}$"),
			BankStart: 1,
			BankEnd: 3,
			AccountStart: 4,
			AccountEnd: 19,
		},
		"SI": {
			Country: "SI",
			Name: "Slovenia",
			Length: 19,
			Regex: regexp.MustCompile("^SI[0-9]{2}[0-9]{5}[0-9]{8}[0-9]{2}$"),
			BankStart: 1,
			BankEnd: 5,
			AccountStart: 6,
			AccountEnd: 13,
		},
		"SK": {
			Country: "SK",
			Name: "Slovakia",
			Length: 24,
			Regex: regexp.MustCompile("^SK[0-9]{2}[0-9]{4}[0-9]{6}[0-9]{10}$"),
			BankStart: 1,
			BankEnd: 4,
			AccountStart: 5,
			AccountEnd: 10,
		},
		"SM": {
			Country: "SM",
			Name: "San Marino",
			Length: 27,
			Regex: regexp.MustCompile("^SM[0-9]{2}[A-Z]{1}[0-9]{5}[0-9]{5}[A-Za-z0-9]{12}$"),
			BankStart: 1,
			BankEnd: 1,
			AccountStart: 2,
			AccountEnd: 6,
		},
		"SO": {
			Country: "SO",
			Name: "Somalia",
			Length: 23,
			Regex: regexp.MustCompile("^SO[0-9]{2}[0-9]{4}[0-9]{3}[0-9]{12}$"),
			BankStart: 1,
			BankEnd: 4,
			AccountStart: 5,
			AccountEnd: 7,
		},
		"ST": {
			Country: "ST",
			Name: "Sao Tome and Principe",
			Length: 25,
			Regex: regexp.MustCompile("^ST[0-9]{2}[0-9]{8}[0-9]{11}[0-9]{2}$"),
			BankStart: 1,
			BankEnd: 8,
			AccountStart: 9,
			AccountEnd: 19,
		},
		"SV": {
			Country: "SV",
			Name: "El Salvador",
			Length: 28,
			Regex: regexp.MustCompile("^SV[0-9]{2}[A-Z]{4}[0-9]{20}$"),
			BankStart: 1,
			BankEnd: 4,
			AccountStart: 5,
			AccountEnd: 24,
		},
		"TL": {
			Country: "TL",
			Name: "Timor-Leste",
			Length: 23,
			Regex: regexp.MustCompile("^TL[0-9]{2}[0-9]{3}[0-9]{14}[0-9]{2}$"),
			BankStart: 1,
			BankEnd: 3,
			AccountStart: 4,
			AccountEnd: 17,
		},
		"TN": {
			Country: "TN",
			Name: "Tunisia",
			Length: 24,
			Regex: regexp.MustCompile("^TN[0-9]{2}[0-9]{2}[0-9]{3}[0-9]{13}[0-9]{2}$"),
			BankStart: 1,
			BankEnd: 2,
			AccountStart: 3,
			AccountEnd: 5,
		},
		"TR": {
			Country: "TR",
			Name: "Turkey",
			Length: 26,
			Regex: regexp.MustCompile("^TR[0-9]{2}[0-9]{5}[0-9]{1}[A-Za-z0-9]{16}$"),
			BankStart: 1,
			BankEnd: 5,
			AccountStart: 6,
			AccountEnd: 6,
		},
		"UA": {
			Country: "UA",
			Name: "Ukraine",
			Length: 29,
			Regex: regexp.MustCompile("^UA[0-9]{2}[0-9]{6}[A-Za-z0-9]{19}$"),
			BankStart: 1,
			BankEnd: 6,
			AccountStart: 7,
			AccountEnd: 25,
		},
		"VA": {
			Country: "VA",
			Name: "Vatican City State",
			Length: 22,
			Regex: regexp.MustCompile("^VA[0-9]{2}[0-9]{3}[0-9]{15}$"),
			BankStart: 1,
			BankEnd: 3,
			AccountStart: 4,
			AccountEnd: 18,
		},
		"VG": {
			Country: "VG",
			Name: "Virgin Islands",
			Length: 24,
			Regex: regexp.MustCompile("^VG[0-9]{2}[A-Z]{4}[0-9]{16}$"),
			BankStart: 1,
			BankEnd: 4,
			AccountStart: 5,
			AccountEnd: 20,
		},
		"XK": {
			Country: "XK",
			Name: "Kosovo",
			Length: 20,
			Regex: regexp.MustCompile("^XK[0-9]{2}[0-9]{4}[0-9]{10}[0-9]{2}$"),
			BankStart: 1,
			BankEnd: 4,
			AccountStart: 5,
			AccountEnd: 14,
		},
		"YE": {
			Country: "YE",
			Name: "Yemen",
			Length: 30,
			Regex: regexp.MustCompile("^YE[0-9]{2}[A-Z]{4}[0-9]{4}[A-Za-z0-9]{18}$"),
			BankStart: 1,
			BankEnd: 4,
			AccountStart: 5,
			AccountEnd: 8,
		},
	}
}
