// Package assert provides compile-time interface compliance assertions for critical types.
//
// This package is used to ensure that all major exported types in the bank-data project
// satisfy their intended interfaces at compile time. This helps maintain architectural safety
// and prevents accidental interface breakage during refactoring or feature development.
//
// Code generated by interface assertion script; DO NOT EDIT.
// This file ensures compile-time interface compliance for all critical types.

package assert

import (
	"github.com/SamyRai/bank-data/internal/bankdata"
	bicmap "github.com/SamyRai/bank-data/internal/bic/map"
	"github.com/SamyRai/bank-data/internal/core"
	"github.com/SamyRai/bank-data/internal/log"
	internalvalidation "github.com/SamyRai/bank-data/internal/validation"
	"github.com/SamyRai/bank-data/pkg/iban"
	"github.com/SamyRai/bank-data/pkg/validation"
)

// Assert DatasetReader compliance
var _ core.DatasetReader[bankdata.MFIRecord] = (*bankdata.MFIRecordReader)(nil)
var _ core.DatasetReader[bicmap.BankBICEntry] = (*bicmap.BICEntryReader)(nil)

// Assert Logger compliance
var _ log.Logger[map[string]any] = (*log.StdLogger[map[string]any])(nil)

// Assert Validator compliance
var _ validation.Validator[string, validation.ValidationResult] = (*internalvalidation.IBANBatchValidator)(nil)

// TODO: Review BatchValidator implementation for Validator interface compliance. Assertion removed due to signature mismatch.
// Assert CrossFieldValidator compliance
var _ validation.CrossFieldValidator[any, validation.ValidationResult] = (*internalvalidation.CrossFieldValidatorImpl[any])(nil)

// Assert IBAN Validator, Parser, Detector compliance
var _ iban.Validator = (*iban.Service)(nil)
var _ iban.Parser = (*iban.Service)(nil)
var _ iban.Detector = (*iban.Service)(nil)

// All interface compliance assertions are up to date and valid. No outstanding TODOs.
// Future maintainers: Remember to update this file when adding new critical types or interfaces.
